# Import necessary dependencies

## USE : Cosine Similarity Algorithm

In [98]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


# Data collection

In [99]:
movies = pd.read_csv('/content/movies.csv')
movies

index  ...           director
0         0  ...      James Cameron
1         1  ...     Gore Verbinski
2         2  ...         Sam Mendes
3         3  ...  Christopher Nolan
4         4  ...     Andrew Stanton
...     ...  ...                ...
4798   4798  ...   Robert Rodriguez
4799   4799  ...       Edward Burns
4800   4800  ...        Scott Smith
4801   4801  ...        Daniel Hsia
4802   4802  ...   Brian Herzlinger

[4803 rows x 24 columns]

# Data PreProcessing

In [100]:
movies.shape

(4803, 24)

In [101]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 24 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   index                 4803 non-null   int64  
 1   budget                4803 non-null   int64  
 2   genres                4775 non-null   object 
 3   homepage              1712 non-null   object 
 4   id                    4803 non-null   int64  
 5   keywords              4391 non-null   object 
 6   original_language     4803 non-null   object 
 7   original_title        4803 non-null   object 
 8   overview              4800 non-null   object 
 9   popularity            4803 non-null   float64
 10  production_companies  4803 non-null   object 
 11  production_countries  4803 non-null   object 
 12  release_date          4802 non-null   object 
 13  revenue               4803 non-null   int64  
 14  runtime               4801 non-null   float64
 15  spoken_languages     

In [102]:
#Hence it is content based movie recommandation system
movies['release_date'] = pd.to_datetime(movies['release_date'])
movies['release_year'] = movies['release_date'].dt.year
Selection_columns = ['original_title','overview','genres','keywords','director','cast','release_year' ]
Selection_columns

['original_title',
 'overview',
 'genres',
 'keywords',
 'director',
 'cast',
 'release_year']

In [103]:
for column in Selection_columns :
  movies[column] = movies[column].fillna('')

In [104]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 25 columns):
 #   Column                Non-Null Count  Dtype         
---  ------                --------------  -----         
 0   index                 4803 non-null   int64         
 1   budget                4803 non-null   int64         
 2   genres                4803 non-null   object        
 3   homepage              1712 non-null   object        
 4   id                    4803 non-null   int64         
 5   keywords              4803 non-null   object        
 6   original_language     4803 non-null   object        
 7   original_title        4803 non-null   object        
 8   overview              4803 non-null   object        
 9   popularity            4803 non-null   float64       
 10  production_companies  4803 non-null   object        
 11  production_countries  4803 non-null   object        
 12  release_date          4802 non-null   datetime64[ns]
 13  revenue           

In [105]:
combined_features = (
    movies['original_title'] + ' ' +
    movies['overview'] + ' ' +
    movies['genres'] + ' ' +
    movies['keywords'] + ' ' +
    movies['director'] + ' ' +
    movies['cast'] + ' ' +
    movies['release_year'].astype(str)
)
combined_features

0       Avatar In the 22nd century, a paraplegic Marin...
1       Pirates of the Caribbean: At World's End Capta...
2       Spectre A cryptic message from Bond’s past sen...
3       The Dark Knight Rises Following the death of D...
4       John Carter John Carter is a war-weary, former...
                              ...                        
4798    El Mariachi El Mariachi just wants to play his...
4799    Newlyweds A newlywed couple's honeymoon is upe...
4800    Signed, Sealed, Delivered "Signed, Sealed, Del...
4801    Shanghai Calling When ambitious New York attor...
4802    My Date with Drew Ever since the second grade ...
Length: 4803, dtype: object

# Feature Extraction

In [106]:
feature_extraction = TfidfVectorizer()
feature_vectors = feature_extraction.fit_transform(combined_features)
print(feature_vectors)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 298415 stored elements and shape (4803, 31199)>
  Coords	Values
  (0, 2092)	0.21139356382754812
  (0, 13691)	0.039072604857179304
  (0, 27573)	0.05803401165477336
  (0, 233)	0.20556342709450523
  (0, 4846)	0.13063299492657363
  (0, 20444)	0.20079985853413376
  (0, 17297)	0.14934370759953516
  (0, 14253)	0.04685512321752404
  (0, 7936)	0.1874533682781637
  (0, 27866)	0.033041508483779965
  (0, 18548)	0.15257340552787094
  (0, 20375)	0.1932835050112066
  (0, 19869)	0.05231812568429324
  (0, 29075)	0.16248844170202822
  (0, 18316)	0.11534178252908095
  (0, 4194)	0.0660077140576067
  (0, 2726)	0.10283547052009527
  (0, 27979)	0.1532701746077026
  (0, 3022)	0.10753763531061866
  (0, 10524)	0.14488572488582122
  (0, 19979)	0.17068346434421247
  (0, 1283)	0.03357846310028717
  (0, 21885)	0.17866225988708057
  (0, 1245)	0.056210169377804535
  (0, 1010)	0.12755564315608642
  :	:
  (4802, 9299)	0.0741724846285323
  (4802, 24504)	0.082

# Getting similarity score with cosine similarity

In [107]:
#Similarity Score
similarity = cosine_similarity(feature_vectors)
print(similarity)

[[1.         0.03296121 0.03070768 ... 0.0172944  0.02866096 0.00637627]
 [0.03296121 1.         0.03040406 ... 0.04129101 0.02941659 0.01460525]
 [0.03070768 0.03040406 1.         ... 0.02371702 0.04639978 0.01042121]
 ...
 [0.0172944  0.04129101 0.02371702 ... 1.         0.03206059 0.04030168]
 [0.02866096 0.02941659 0.04639978 ... 0.03206059 1.         0.02868781]
 [0.00637627 0.01460525 0.01042121 ... 0.04030168 0.02868781 1.        ]]


In [108]:
similarity.shape

(4803, 4803)

In [109]:
#List of movies
movies_list = movies['original_title'].tolist()
movies_list

['Avatar',
 "Pirates of the Caribbean: At World's End",
 'Spectre',
 'The Dark Knight Rises',
 'John Carter',
 'Spider-Man 3',
 'Tangled',
 'Avengers: Age of Ultron',
 'Harry Potter and the Half-Blood Prince',
 'Batman v Superman: Dawn of Justice',
 'Superman Returns',
 'Quantum of Solace',
 "Pirates of the Caribbean: Dead Man's Chest",
 'The Lone Ranger',
 'Man of Steel',
 'The Chronicles of Narnia: Prince Caspian',
 'The Avengers',
 'Pirates of the Caribbean: On Stranger Tides',
 'Men in Black 3',
 'The Hobbit: The Battle of the Five Armies',
 'The Amazing Spider-Man',
 'Robin Hood',
 'The Hobbit: The Desolation of Smaug',
 'The Golden Compass',
 'King Kong',
 'Titanic',
 'Captain America: Civil War',
 'Battleship',
 'Jurassic World',
 'Skyfall',
 'Spider-Man 2',
 'Iron Man 3',
 'Alice in Wonderland',
 'X-Men: The Last Stand',
 'Monsters University',
 'Transformers: Revenge of the Fallen',
 'Transformers: Age of Extinction',
 'Oz: The Great and Powerful',
 'The Amazing Spider-Man 2',

# Final Movie Recommandation System

In [112]:
movie_input = input('Enter your movie name : ')

find_closest_match = difflib.get_close_matches(movie_input, movies_list)
if find_closest_match :
    close_match = find_closest_match[0]

    # finding the index of movie
    index_close_match_movie = movies[movies['original_title'] == close_match]['index'].values[0]

    #Getting List of similar movies
    similarity_score = list(enumerate(similarity[index_close_match_movie]))

    sorted_similar_movies = sorted(similarity_score, key= lambda x:x[1], reverse=True)
    final_similar_movies = sorted_similar_movies[0:21]

    #Suggestion of movies

    print('Suggested Movies : \n')

    i=1

    for movie in final_similar_movies :
      index = movie[0]
      title_from_index = movies[movies.index == index]['original_title'].values[0]
      print(title_from_index)
else :
  print('Movie not found')

Enter your movie name : disney
Suggested Movies : 

Ondine
Splash
Jindabyne
Trade
Aquamarine
Sommersturm
Miss Julie
The Perfect Storm
The Shipping News
Michael Collins
The Net
Bran Nue Dae
Everything Must Go
Snow Falling on Cedars
Winter's Tale
The Wind That Shakes the Barley
Big Fish
Seven Psychopaths
Dead Man Down
Pan
Jaws
